proxy: ""        #浏览器使用的代理
quest_proxy: ""  #sd api请求时使用的代理地址，如果开启代理后，Achernar反代不能正常工作请填写此项。你代理软件的http代理地址。
port: 3529
shared_notebook: "dania-fix.ipynb"    #ipynb文件下载到本地
enable_kaggle_extension: true
enable_cpolar_extension: true
enable_get_dynamic_ip: false   #你一般用不到，这是个人提供的frp服务。不可与cpolar同时开启
cpolar_check_interval: 180
kaggle_change_account_interval: 43050

kaggle_accounts:
  - username: "方便你自己记的账户名"
    key: "KGAT_xxxxxx"
  - username: "方便你自己记的账户名"
    key: "KGAT_xxxxxx"
cpolar:
  email: "cpolar的邮箱"
  password: "cpolar的密码"
get_dynamic_ip:   #通过url获取动态ip
  url: ""
  port1: 11111
  port2: 22222
