cpolar_check_interval = 180
enable_cpolar_extension = true
enable_get_dynamic_ip = false
enable_kaggle_extension = true
headless = true
kaggle_change_account_interval = 43050
port = 3529
proxy = ""
quest_proxy = ""
shared_notebook = ""

[cpolar]
email = "cpolar的邮箱"
password = "cpolar的密码"

[get_dynamic_ip]
port1 = 11111
port2 = 22222
url = ""

[[kaggle_accounts]]
email = "你的邮箱"
password = "你的密码"

[[kaggle_accounts]]
email = "你的第二个邮箱"
password = "你的第二个密码"
