proxy: ""        #这一项没用，别填，填了出问题。
quest_proxy: ""  #sd api请求时使用的代理地址，如果开启代理后，Achernar反代不能正常工作请填写此项。你代理软件的http代理地址。
port: 3529
headless: true   #是否开启浏览器无头模式，低配服务器建议开启。
#在shared_notebook填入记录的你的【分享链接】
shared_notebook: ""
enable_kaggle_extension: true
enable_cpolar_extension: true
enable_get_dynamic_ip: false   #你一般用不到，这是个人提供的frp服务。
cpolar_check_interval: 180
kaggle_change_account_interval: 43050

kaggle_accounts:
  - email: "你的邮箱"
    password: "你的密码"
  - email: "你的第二个邮箱"
    password: "你的第二个密码"  #以此类推
cpolar:
  email: "cpolar的邮箱"
  password: "cpolar的密码"
get_dynamic_ip:   #通过url获取动态ip
  url: ""
  port1: 11111
  port2: 22222