proxy: ""     #没用，不用管这一项
port: 3529
#在shared_notebook填入上面记录的你的【分享链接】
shared_notebook: ""
enable_kaggle_extension: true
enable_cpolar_extension: true
cpolar_check_interval: 3600
kaggle_change_account_interval: 36000

kaggle_accounts:
  - email: "你的kaggle账号"
    password: "密码"
  - email: "你的第二个kaggle账号"
    password: "密码"  #以此类推
cpolar:
  email: "你的cpolar账号"
  password: "密码"